spring.application.name=booking

# Postgresql data connection
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=1234


#SQL configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis Server Connection
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=yourpassword (if applicable)

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000ms 
spring.cache.redis.cache-null-values=false

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
